### ISSUE TITLE
Bugs Compilation 2

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#105] opened 2023-11-14 10:46 UTC
- [x] When a user tries to create a proposal without having enough tokens, a modal appears explaining it, but this modal cannot be closed. 
- [x] After voting, the voter can "revote" (see the "Vote" button) but then the previous modal appears. After reloading, everything works well, but without reloading it seems that you didn't vote (the "Voters" page don't show the new vote).
- [x] When clicking on "Voters", a "No voters yet" appears, after a while the voters appears. Add a loader on this component? 

- [x] (failed) GET call to `https://api-stg.vocdoni.net/v2/elections/0x0000000000000000000000000000000000000000000000000000000000000000` in the Dashboard "Governance" page
- [x] Clicking on "Voters" component on "Approvers" area, breaks the page:

![Image](https://github.com/vocdoni/interoperability/assets/6894329/ed1c689c-a40c-44a4-b96b-94e14db79eb5)

- [x] In "approvers" element, in the "Info" tab, this string appears: Strategy key 'votingTerminal.multisig (en)' returned an object instead of string.
- [x] In the "approvers" element, in the "Info" tab, the information is not correct (status: "Defeted"). It shows "Reached" even with 0 approvals. Also instead of the "end date" being the end_date+expiration_date, it shows another text: 

![Image](https://github.com/vocdoni/interoperability/assets/6894329/b36b6fa5-c3a3-4ae1-843f-28469c583a3b)

Also, the text shows: "Approval period is not open yet" but the approval period is already ended:

![Image](https://github.com/vocdoni/interoperability/assets/6894329/a42e4876-ef45-4547-bdb3-23a052121a16)

**Comment by nigeon** [comment] 2023-11-14 11:15
-> When a user tries to create a proposal without having enough tokens, a modal appears explaining it, but this modal cannot be closed.

This looks like it's an Aragon issue.

->  After voting, the voter can "revote" (see the "Vote" button) but then the previous modal appears. After reloading, everything works well, but without reloading it seems that you didn't vote (the "Voters" page don't show the new vote).
-> When clicking on "Voters", a "No voters yet" appears, after a while the voters appears. Add a loader on this component?

Looks like there's no auto-reload/auto-refresh in this page, again, this should be implemented by Aragon App.

**Comment by nigeon** [comment] 2023-11-17 12:49
-> "Approval period is not open yet" but the approval period is already ended:
Couldn't reproduce

**Comment by selankon** [comment] 2023-12-05 10:43
> When a user tries to create a proposal without having enough tokens, a modal appears explaining it, but this modal cannot be closed.

This maybe is related to a modal bug which could be solved already

**Comment by selankon** [comment] 2023-12-05 10:43
> After voting, the voter can "revote" (see the "Vote" button) but then the previous modal appears. After reloading, everything works well, but without reloading it seems that you didn't vote (the "Voters" page don't show the new vote).

Should be fixed after cache implemented.

**Comment by selankon** [comment] 2023-12-05 10:45
> When clicking on "Voters", a "No voters yet" appears, after a while the voters appears. Add a loader on this component?
 
This happen also on a non gasless voting DAO? Is an aragon component, should we fix it or maybe we can open an issue to them?

**Comment by selankon** [comment] 2023-12-05 10:48
> (failed) GET call to https://api-stg.vocdoni.net/v2/elections/0x0000000000000000000000000000000000000000000000000000000000000000 in the Dashboard "Governance" page

This is related to this https://github.com/vocdoni/interoperability/issues/106 .

**Closed** 2023-12-14 15:07 UTC
