### ISSUE TITLE
Final Bug Compilation

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#108] opened 2023-12-12 07:46 UTC
### Generic Bugs:

- [x] You can create a dao and set approval days to 0, no error is shown and Next button is activated

- [x] Members component is showing multisig members and not token holders. 

- [x] ~~Use existing mintable token does not read properly the token amount~~ (Subgraph issue)

- [x] Created a DAO importing a existing token, and the "DAO Members" page is empty (at the beggining I though it will be bc the token is still being scanned, but after 30 min, nothing has changed). After a while, only 1 token holder appears ("you"). Then it disappears and 0 members is show again... It happens every time I click the "Members page" from the "Tokenholders" link or the header.
DAO: https://ipfs.eth.aragon.network/ipfs/QmfYKEhRe3GJUiSqMuqTQC2Cb21LpkQ2kXhu4bkb3L2mXk/#/daos/goerli/mnktest.dao.eth/dashboard

- [x] Also, when clicking into the "Dashboard", the `Members` component appears and disappears. 

- [x] In the "Create DAO - Review DAO" step, the "Early execution" and "Vote Change" shouldn't appear (or at least appear as "No"). Also, make sure that the 2 parameters are set to "no" in all cases. Same in "Settings" page.

- [x] In the "Edit Settings" page, the "Governance" tab is empty: 

![image](https://github.com/vocdoni/interoperability/assets/6894329/3c41b27a-d056-4bf0-82fd-4b2e8a7c47f2)

Vote page:
- [x] In the "Actions approval" -> "Info" tab, when 0 approvals are set, the label/texts says "Reached" - "No approvals missing", instead of "Pending" or "Not started" or similar: 

![image](https://github.com/vocdoni/interoperability/assets/6894329/2f6a6987-578c-4e0b-b18c-910a3b9eff27)

- [x] Due to small differences between the end of process onchain and offchain this error message may appear to the user.
It should be caught  (ideally from an vocdoni SDK typed error) and printed better

![Image](https://github.com/vocdoni/interoperability/assets/2574087/11676ee8-d97e-49ac-9676-5445d9cb24e7)

- [x] We should differentiate or improve and review all the labels with time in the proposals, as now it get mixed the "Voting" time with the "Approve and Execute" time, resulting in confusing messages:

I.E - The vote text shows "Ends in 34 min" when it should be "Ended in 34 min." 

![Image](https://github.com/vocdoni/interoperability/assets/6894329/2052164f-544c-4e6c-bddf-8fc096d1e518)

- [x] Review timestamp on active proposal card 

![image](https://github.com/vocdoni/interoperability/assets/16777076/7c933032-b7c0-464c-aae9-d1607c2af281)

### Translations: 
- [x] Missing Translations:
      - Settings Page: `navLinks.executionMultisig`
      - Settings Page: `labels.review.members` 
 
### Proposal Creation Bugs:
      
- [x] **Cannot create proposal.** Errors:
      - 0 Undefined:
![image](https://github.com/vocdoni/interoperability/assets/6894329/06ed6b17-1667-4437-af34-62b07fc7a321)

      - Token error:
![image](https://github.com/vocdoni/interoperability/assets/6894329/3b319ec1-bb3a-4646-8434-6cad25540f2e)

       -  Account does not exist:
![image](https://github.com/vocdoni/interoperability/assets/6894329/9273eae0-6624-417d-bffc-a421a71c6b02)

- Wallet already funded:
![image](https://github.com/vocdoni/interoperability/assets/6894329/d7662980-ee2b-4e86-b07c-e70c8a37bb62)

**Comment by selankon** [comment] 2023-12-13 15:37
> In the "Create DAO - Review DAO" step, the "Early execution" and "Vote Change" shouldn't appear (or at least appear as "No"). Also, make sure that the 2 parameters are set to "no" in all cases. Same in "Settings" page.

I hide it after https://github.com/aragon/app/commit/81e61f99401a9f93c5ac9718053589b6416f3863

**Comment by selankon** [comment] 2023-12-13 15:58
> Missing nº of approvals needed in the "Settings page" (x of 1 authorized addresses -> "x" is missing)

It seems the actual string is wrong https://github.com/aragon/app/blob/378bee04cfe5c42d47f91578e551a7a6acefa4fb/src/locales/en/common.json#L175

When updated remember to update also the review create dao https://github.com/aragon/app/blob/378bee04cfe5c42d47f91578e551a7a6acefa4fb/src/containers/goLive/committee.tsx#L100

**Comment by selankon** [comment] 2023-12-13 16:00
> Missing translations 

- [x] Settings Page: `navLinks.executionMultisig`
- [x] Settings Page: `labels.review.members` 

Both fixed on the `f/gasless-propose-settings` brancj

**Comment by selankon** [comment] 2023-12-13 16:04
> In the "Edit Settings" page, the "Governance" tab is empty:

Fixed on the `f/gasless-propose-settings` branch

**Comment by selankon** [comment] 2023-12-13 16:37
> In the "Actions approval" -> "Info" tab, when 0 approvals are set, the label/texts says "Reached" - "No approvals missing", instead of "Pending" or "Not started" or similar:

Should be fixed on  

https://github.com/aragon/app/commit/ee75ef11

**Comment by selankon** [comment] 2023-12-18 10:23
> Created a DAO importing a existing token, and the "DAO Members" page is empty (at the beggining I though it will be bc the token is still being scanned, but after 30 min, nothing has changed). After a while, only 1 token holder appears ("you"). Then it disappears and 0 members is show again... It happens every time I click the "Members page" from the "Tokenholders" link or the header.
> DAO: https://ipfs.eth.aragon.network/ipfs/QmfYKEhRe3GJUiSqMuqTQC2Cb21LpkQ2kXhu4bkb3L2mXk/#/daos/goerli/mnktest.dao.eth/dashboard
> Also, when clicking into the "Dashboard", the Members component appears and disappears.

I cannot reproduce it, on my localhost branch everything works as expected. Two members appear. 

BTW, the token holders members are shown using a third party library afair. So if the token holders are not scanned properly is probably an issue with this library. Let me know if i have to look deeper on it, for the moment i marked the issues as resolved.

**Comment by selankon** [comment] 2023-12-18 11:39
>  Review timestamp on active proposal card

https://github.com/aragon/app/commit/d3e15c8c

**Comment by selankon** [comment] 2023-12-22 08:31
> You can create a dao and set approval days to 0, no error is shown and Next button is activated

https://github.com/aragon/app/commit/49073ccc

**Comment by jpaulet** [comment] 2024-01-02 14:22
- [ ] New visual bug on the Dashboard, when 1 token-holder, the list is not rendered properly: 

![image](https://github.com/vocdoni/interoperability/assets/6894329/b4e9f51b-3e1c-4104-bfe1-a55820b31ea6)

**Closed** 2024-01-23 15:08 UTC
